// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecruitmentAgency.Domain.Context;

#nullable disable

namespace RecruitmentAgency.Domain.Migrations
{
    [DbContext(typeof(RecruitmentAgencyContext))]
    partial class RecruitmentAgencyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RecruitmentAgency.Domain.Entity.Applicant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactInformation")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("contactinfo");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("education");

                    b.Property<double>("Experience")
                        .HasMaxLength(50)
                        .HasColumnType("double")
                        .HasColumnName("experience");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("fullname");

                    b.Property<int>("Salaries")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("salaries");

                    b.HasKey("Id");

                    b.ToTable("applicant");
                });

            modelBuilder.Entity("RecruitmentAgency.Domain.Entity.ApplicantApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("submission_date");

                    b.Property<int>("applicant_id")
                        .HasColumnType("int");

                    b.Property<int>("position_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("applicant_id");

                    b.HasIndex("position_id");

                    b.ToTable("applicant_application");
                });

            modelBuilder.Entity("RecruitmentAgency.Domain.Entity.Employer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("company_name");

                    b.Property<string>("CompanyNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("company_number");

                    b.Property<string>("ContactPersonName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("contact_person_name");

                    b.HasKey("Id");

                    b.ToTable("employer");
                });

            modelBuilder.Entity("RecruitmentAgency.Domain.Entity.EmployerApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OfferedSalary")
                        .HasColumnType("int")
                        .HasColumnName("offered_salary");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("requirements");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("submission_date");

                    b.Property<int>("employer_id")
                        .HasColumnType("int");

                    b.Property<int>("position_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("employer_id");

                    b.HasIndex("position_id");

                    b.ToTable("employer_application");
                });

            modelBuilder.Entity("RecruitmentAgency.Domain.Entity.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("position_name");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("section");

                    b.HasKey("Id");

                    b.ToTable("position");
                });

            modelBuilder.Entity("RecruitmentAgency.Domain.Entity.ApplicantApplication", b =>
                {
                    b.HasOne("RecruitmentAgency.Domain.Entity.Applicant", "Applicant")
                        .WithMany()
                        .HasForeignKey("applicant_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentAgency.Domain.Entity.Position", "Position")
                        .WithMany()
                        .HasForeignKey("position_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("RecruitmentAgency.Domain.Entity.EmployerApplication", b =>
                {
                    b.HasOne("RecruitmentAgency.Domain.Entity.Employer", "Employer")
                        .WithMany()
                        .HasForeignKey("employer_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentAgency.Domain.Entity.Position", "Position")
                        .WithMany()
                        .HasForeignKey("position_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employer");

                    b.Navigation("Position");
                });
#pragma warning restore 612, 618
        }
    }
}
