<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Components\Pages\" />
  </ItemGroup>
	
    <ItemGroup>
	    <OpenApiReference Include="Api\swagger.json" ClassName="RecruitmentAgencyApi" CodeGenerator="NSwagCSharp" />
    </ItemGroup>
	
  <ItemGroup>
    <PackageReference Include="Blazorise" Version="1.7.0" />
    <PackageReference Include="Blazorise.Bootstrap" Version="1.7.0" />
    <PackageReference Include="Blazorise.Bootstrap5" Version="1.7.0" />
    <PackageReference Include="Blazorise.Components" Version="1.7.0" />
    <PackageReference Include="Blazorise.DataGrid" Version="1.7.0" />
    <PackageReference Include="Blazorise.Icons.FontAwesome" Version="1.7.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NSwag.ApiDescription.Client" Version="14.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RecruitmentAgency.API\RecruitmentAgency.API.csproj" />
  </ItemGroup>

</Project>
